In [6]:
import numpy as np

def scaled_dot_product_attention(Q, K, V):
    # Step 1: Dot product of Q and Kᵀ
    dk = Q.shape[-1]
    scores = np.dot(Q, K.T)

    # Step 2: Scale the scores
    scaled_scores = scores / np.sqrt(dk)

    # Step 3: Apply softmax to get attention weights
    exp_scores = np.exp(scaled_scores - np.max(scaled_scores, axis=1, keepdims=True))  # stability trick
    attention_weights = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    # Step 4: Multiply attention weights with V
    output = np.dot(attention_weights, V)

    # Print results
    print("Attention Weights:\n", attention_weights)
    print("Output:\n", output)

# Test input
Q = np.array([[1, 0, 1, 0],
              [0, 1, 0, 1]])
K = np.array([[1, 0, 1, 0],
              [0, 1, 0, 1]])
V = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

scaled_dot_product_attention(Q, K, V)


Attention Weights:
 [[0.73105858 0.26894142]
 [0.26894142 0.73105858]]
Output:
 [[2.07576569 3.07576569 4.07576569 5.07576569]
 [3.92423431 4.92423431 5.92423431 6.92423431]]


1. Why divide the attention score by √d in scaled dot-product attention?
We divide by √d to prevent the dot product values from becoming too large, which can push softmax into very small gradients and make learning unstable.

2. How does self-attention help the model understand relationships between words in a sentence?
Self-attention allows each word to focus on other words in the sentence, capturing dependencies and context regardless of their position.

